baseURL = 'https://taekgeun0816-creator.github.io/TGKIM/'
languageCode = 'ko-kr'
title = 'TGKIM Archive'
theme = 'ananke'

[params]
  description = "흥미로운 생각과 일상의 기록들"
  
  # 1. 하위 경로(/TGKIM/)를 사용하는 깃허브 페이지 특성을 고려해 맨 앞 슬래시(/)를 제거합니다.
  featured_image = "images/feature.jpg"
  
  # 2. 배경색 클래스가 활성화되어 있으면 이미지를 가릴 수 있으므로 투명(bg-transparent)하게 만들거나 비워둡니다.
  background_color_class = "bg-transparent" 
  
  recent_posts_number = 3

  custom_css = ["css/custom.css"]